name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: typo3_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3']
        typo3-version: ['^12.4', '^13.4']
        exclude: []

    name: PHP ${{ matrix.php-version }} / TYPO3 ${{ matrix.typo3-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, pdo_mysql, pdo_sqlite, mbstring
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "typo3/cms-core:${{ matrix.typo3-version }}" --no-update
          composer require "typo3/cms-frontend:${{ matrix.typo3-version }}" --no-update --dev
          composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Setup database for functional tests
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS typo3_test;"
          mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON typo3_test.* TO 'root'@'%';"

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite "Unit Tests"

      - name: Run functional tests
        env:
          typo3DatabaseName: typo3_test
          typo3DatabaseUsername: root
          typo3DatabasePassword: root
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseDriver: pdo_mysql
        run: vendor/bin/phpunit -c phpunit-functional.xml

      # Coverage disabled per project decision

  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, pdo_sqlite, mbstring
          tools: composer:v2, phpstan, php-cs-fixer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-8.3-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-8.3-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Check PHP syntax
        run: find Classes Tests -name "*.php" -exec php -l {} \;

      # Uncomment when phpstan is configured
      # - name: Run PHPStan
      #   run: phpstan analyse Classes --level 5

      # Uncomment when php-cs-fixer is configured
      # - name: Run PHP CS Fixer
      #   run: php-cs-fixer fix --dry-run --diff
